version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.2

shared: &shared
  steps:
    - checkout
    - run:
        name: Install Chromedriver latest version
        command: |
          sudo apt-get install xvfb
    - browser-tools/install-chrome
    - run:
        name: Install Python deps in a venv
        command: |
          sudo pip install --upgrade pip
          pip install -r ext/requirements-dev.txt
    - run:
        name: Running tests
        command: |
          coverage run -m unittest tests/test_main.py
    - run: |
        if [ $UPLOAD_COV ]; then
          codecov
        fi

jobs:
  py39:
    <<: *shared
    docker:
      - image: circleci/python:3.9

  py310:
    <<: *shared
    docker:
      - image: circleci/python:3.10

  py311:
    <<: *shared
    docker:
      - image: circleci/python:3.11

  py312:
    <<: *shared
    docker:
      - image: circleci/python:3.11

  py313:
    <<: *shared
    docker:
      - image: circleci/python:3.13
        environment:
          UPLOAD_COV: "true"

workflows:
  version: 2.1
  main:
    jobs:
      - py39
      - py310
      - py311
      - py312
      - py313
